name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "15 10 * * *"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ⬇️ Install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # ⬇️ Install any R packages your scripts need
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("readr", "dplyr", "jsonlite", "tidyr"), repos = "https://cloud.r-project.org")'

      # ⬇️ Run your data loader R scripts
      - name: Run data loaders
        run: |
          Rscript src/data/dfiFull.csv.R
          # Add more R scripts here if needed

      # ⬇️ Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # ⬇️ Install project deps
      - run: npm ci

      # ⬇️ Build Observable site
      - run: npm run build

      # ⬇️ Configure and deploy GitHub Pages
      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
